services:
  blogapp:
    container_name: linkgraph-toy-blogapp
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    command: tail -f /dev/null
    ports:
      - "5700:5700"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}:5432/${POSTGRES_DB}
      - DATABASE_PORT=5432
    env_file:
      - .env

  db:
    container_name: linkgraph-toy-db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  redis:
    container_name: linkgraph-toy-redis
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
    - redis_data:/data

volumes:
  postgres_data:
  redis_data:
